[WIP] PT-28 Use webpack instead of gulp to compile backend project on boilerplate
jalantechnologies/boilerplate-mern pull request #36
Opened 2022-09-23 06:38 UTC by akashlakhera

## Description

Use webpack instead of gulp to compile backend project on boilerplate

2022-09-29 06:37 UTC, bbbneo333 commented
@akashlakhera - Encountered following issue when ran `docker compose -f docker-compose.dev.yml up --build`, can you please check?

<img width="1728" alt="Screenshot 2022-09-29 at 12 04 42 PM" src="https://user-images.githubusercontent.com/23015711/192956793-68597da3-00bf-4380-a32f-55261103498e.png">

2022-09-30 06:16 UTC, bbbneo333 commented
Hey @akashlakhera, while testing out the new build system, noticed that when there's is change in backend, it tries to build the frontend as well (please see video, atleast according to the logs it looks like it but might be wrong). 

https://user-images.githubusercontent.com/23015711/193202100-dc8e370f-94a9-4a09-ab69-bbf5e57f52be.mov

2022-09-30 07:10 UTC, bbbneo333 requested changes

2022-09-30 07:10 UTC, bbbneo333 commented on config/webpack/webpack.prod.js
> +/* eslint-disable import/no-extraneous-dependencies */
See note from above

2022-09-30 07:10 UTC, bbbneo333 commented on config/webpack/webpack.prod.js
> +const path = require('path');
Think these can be removed

2022-09-30 11:09 UTC, akashlakhera commented on config/webpack/webpack.common.js
> +    new webpack.DefinePlugin({ CONFIG: JSON.stringify(CONFIG) }),
This should not inject entire configuration according to [docs](https://github.com/node-config/node-config/wiki/Webpack-Usage#option-1).

2022-09-30 12:48 UTC, bbbneo333 commented on config/webpack/webpack.common.js
> +    new webpack.DefinePlugin({ CONFIG: JSON.stringify(CONFIG) }),
Still, don't think this is still something we should be doing. As mentioned:
- Define a `public` config which is dedicated to frontend. Nothing else should injected (irrespective of env)
- The type we have defined for config (`const CONFIG: { [key: string]: { [key: string]: string } };`) should be explicit. 

Say if we have:
```json
{
  "public": {
    "some_config": "some value"
  }
}
```

We should have type definition as:
```typescript
type Config = {
  'some_config': string
};
```

And we should be able to use it as `Config.some_config` in frontend.

2022-09-30 12:49 UTC, bbbneo333 commented on src/public/js/ui/app.tsx
> +    console.log(CONFIG.server.port);
Can show the current env on homepage instead

2022-10-06 09:02 UTC, closed without merging